/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.event.*;
import javax.swing.plaf.*;
/**
 *
 * @author MARTHA
 */
public class Ventana extends javax.swing.JFrame {
    
    private DefaultComboBoxModel<Persona> modelo = new DefaultComboBoxModel<Persona>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    /**
     * Creates new form Ventana
     */
    public Ventana() {    
        llenarModeloComboBox();
        agregarModeloTabla();
        initComponents();
        setLocationRelativeTo(null);
    }
    private void agregarModeloTabla(){
        modeloTabla.addColumn("NOMBRES");
        modeloTabla.addColumn("APELLIDOS");
        modeloTabla.addColumn("EMAIL");
        modeloTabla.addColumn("CELULAR");
        modeloTabla.addColumn("DIRECCION");
        
    }
    
    private void llenarModeloComboBox(){
        modelo.addElement(new Persona("Carlos","Hernandez","Carlos@gmail.com","321-335-0991","El Paraiso"));
        modelo.addElement(new Persona("Yecid","Hernandez","Yecid@gmail.com","321-335-0992","El Paraiso"));
        modelo.addElement(new Persona("Miller","Hernandez","Miller@gmail.com","321-335-0993","El Paraiso"));
        modelo.addElement(new Persona("Jarvey","Hernandez","Jarvey@gmail.com","321-335-0994","El Paraiso"));
        modelo.addElement(new Persona("Yurley","Hernandez","Yurley@gmail.com","321-335-0995","El Paraiso"));
        modelo.addElement(new Persona("Leidy","Hernandez","Leidy@gmail.com","321-335-0996","El Paraiso"));
        modelo.addElement(new Persona("Yineth","Hernandez","Yineth@gmail.com","321-335-0997","El Paraiso"));
        modelo.addElement(new Persona("Anyi","Hernandez","Anyi@gmail.com","321-335-0998","El Paraiso"));
        modelo.addElement(new Persona("Didiher","Hernandez","Didiher@gmail.com","321-335-0999","El Paraiso"));
        modelo.addElement(new Persona("Stiven","Hernandez","Stiven@gmail.com","321-335-0910","El Paraiso"));
        modelo.addElement(new Persona("Martha","Hernandez","Martha@gmail.com","321-335-0911","El Paraiso"));

        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaPersonas = new javax.swing.JLabel();
        ComboPersonas = new javax.swing.JComboBox<>();
        BotonInsertar = new javax.swing.JButton();
        jScrollTabla = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Separador = new javax.swing.JSeparator();
        Datospersona = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        etiquetaApellidos = new javax.swing.JLabel();
        CajaApellidos = new javax.swing.JTextField();
        EtiquetaEmail = new javax.swing.JLabel();
        EtiquetaCelular = new javax.swing.JLabel();
        CajaMail = new javax.swing.JTextField();
        CajaCelular = new javax.swing.JTextField();
        EtiquetaDireccion = new javax.swing.JLabel();
        CajaDireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaPersonas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaPersonas.setText("Persona");

        ComboPersonas.setModel(modelo);

        BotonInsertar.setText("Insertar Persona");
        BotonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarActionPerformed(evt);
            }
        });

        Tabla.setModel(modeloTabla);

        ListSelectionListener oyenteSeleccion = new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent e){
                if(e.getValueIsAdjusting()){  
                    int filaSeleccionada = Tabla.getSelectedRow();

                    String nombre = (String)modeloTabla.getValueAt(filaSeleccionada,0);
                    String apellidos = (String)modeloTabla.getValueAt(filaSeleccionada,1);
                    String email = (String)modeloTabla.getValueAt(filaSeleccionada,2);
                    String celular = (String)modeloTabla.getValueAt(filaSeleccionada,3);
                    String direccion = (String)modeloTabla.getValueAt(filaSeleccionada,4);

                    CampoNombre.setText(nombre);
                    CajaApellidos.setText(apellidos);
                    CajaMail.setText(email);
                    CajaCelular.setText(celular);
                    CajaDireccion.setText(direccion);
                }   
            }

        };

        Tabla.getSelectionModel().addListSelectionListener(oyenteSeleccion);
        jScrollTabla.setViewportView(Tabla);

        Datospersona.setText("Datos de la Persona");

        etiquetaNombre.setText("Nombre:");

        etiquetaApellidos.setText("Apellido:");

        EtiquetaEmail.setText("E-mail:");

        EtiquetaCelular.setText("Celular:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(etiquetaPersonas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(ComboPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollTabla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addComponent(Datospersona)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Separador))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombre)
                    .addComponent(EtiquetaEmail)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaCelular)
                    .addComponent(etiquetaApellidos)
                    .addComponent(CajaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonInsertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Datospersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(etiquetaApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CajaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaEmail)
                    .addComponent(EtiquetaCelular)))
        );

        EtiquetaDireccion.setText("Direccion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EtiquetaDireccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CajaMail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(CajaCelular))
                    .addComponent(CajaDireccion))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CajaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EtiquetaDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarActionPerformed
        // TODO add your handling code here:
        Persona p =(Persona)ComboPersonas.getSelectedItem();
        
        String nombres = p.getNombres();
        String apellidos = p.getApellidos();
        String email = p.getEmail();
        String celular=p.getCelular();
        String direccion=p.getDireccion();
        
        String [] persona={nombres,apellidos,email,celular,direccion};
        
        modeloTabla.addRow(persona);
    }//GEN-LAST:event_BotonInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JTextField CajaApellidos;
    private javax.swing.JTextField CajaCelular;
    private javax.swing.JTextField CajaDireccion;
    private javax.swing.JTextField CajaMail;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JComboBox<Persona> ComboPersonas;
    private javax.swing.JLabel Datospersona;
    private javax.swing.JLabel EtiquetaCelular;
    private javax.swing.JLabel EtiquetaDireccion;
    private javax.swing.JLabel EtiquetaEmail;
    private javax.swing.JSeparator Separador;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPersonas;
    private javax.swing.JScrollPane jScrollTabla;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
